# weasel.yaml 支持的所有选项及注释，用于配置参考
# 定制化文档 https://github.com/rime/weasel/wiki/Weasel-定製化

# 在用户使用「输入法设定」调整设置时，小狼毫会格式化 weasel.custom.yaml，删除所有注释。
# 目前建议的自定义方法：复制此本文件并修改，之后在 weasel.custom.yaml 用 `__include` 引入。示例 weasel.custom.yaml 如下：
# patch:
#   "preset_color_schemes/+":
#     __include: "weasel_style_copy:/preset_color_schemes"
#   "style/+":
#     __include: "weasel_style_copy:/style"
style:
  font_face: "LXGW WenKai"
  font_point: 17
  text_orientation: horizontal
  inline_preedit: false
  candidate_list_layout: linear
  color_scheme: dark_color
  preedit_type: composition
  corner_radius: 8
  round_corner: 7
  border_width: 3
  spacing: 10

app_opt:
  app_options/com.mitchellh.ghostty/vim_mode: true

preset_color_schemes:
  dark_color:
    name: dark_color
    author: parsifa1 <li.aldric@gmail.com>, based on dark_temple
    text_color: 0xE2CCFF
    candidate_text_color: 0xd8e3e6
    back_color: 0x222222
    border_color: 0x222222
    hilited_text_color: 0xffcf9a
    hilited_back_color: 0x222222
    hilited_candidate_text_color: 0xE2CCFF
    hilited_candidate_back_color: 0x333333
    comment_text_color: 0x606cff
